version: '3'
services:
  balancer:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    expose:
      - 5000
    depends_on:
      - db

  db:
    image: postgres
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "postgres",
          "-U",
          "${POSTGRES_USER}"
        ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=qasim
      - POSTGRES_PASSWORD=qasim
      - POSTGRES_DB=pushups
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
